//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REDZONE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSC_CUSTOMER
    {
        public int dsc_cust_id { get; set; }
        public string dsc_cust_name { get; set; }
        public string dsc_cust_parent_name { get; set; }
        public Nullable<System.DateTime> dsc_cust_eff_end_date { get; set; }
    }
}
