//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REDZONE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTRC_METRIC_PRODUCTS
    {
        public int mtrc_prod_id { get; set; }
        public short prod_id { get; set; }
        public int mtrc_period_id { get; set; }
    
        public virtual MTRC_PRODUCT MTRC_PRODUCT { get; set; }
        public virtual MTRC_METRIC_PERIOD MTRC_METRIC_PERIOD { get; set; }
    }
}
