//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REDZONE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTRC_MGMT_AUTH
    {
        public short mma_id { get; set; }
        public int mtrc_prod_id { get; set; }
        public string mma_dsc_ad_username { get; set; }
        public System.DateTime mma_eff_start_date { get; set; }
        public System.DateTime mma_eff_end_date { get; set; }
    
        public virtual MTRC_METRIC_PRODUCTS MTRC_METRIC_PRODUCTS { get; set; }
    }
}
