//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REDZONE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTRC_DATA_SRC
    {
        public short data_src_id { get; set; }
        public string data_src_name { get; set; }
        public string data_src_desc { get; set; }
        public string data_src_type { get; set; }
        public string data_src_conn_str { get; set; }
    }
}
